// Full dropzone database with coordinates
export const DROPZONE_DATABASE = [
   { id: "1", name: "Chicagoland Skydiving Center", country: "United States", city: "Rochelle IL", latitude: 41.8926, longitude: -89.0796, elevation: 238 },
  { id: "2", name: "Skydive Deland", country: "United States", city: "DeLand FL", latitude: 29.067, longitude: -81.2837, elevation: 24 },
  { id: "3", name: "Skydive Elsinore", country: "United States", city: "Lake Elsinore CA", latitude: 33.63, longitude: -117.3017, elevation: 382 },
  { id: "4", name: "Skydive Arizona", country: "United States", city: "Eloy AZ", latitude: 32.8067, longitude: -111.5866, elevation: 461 },
  { id: "5", name: "Skydive Fyrosity", country: "United States", city: "Overton NV", latitude: 36.5681, longitude: -114.4433, elevation: 416 },
  { id: "6", name: "Skydive Kapowsin", country: "United States", city: "Shelton WA", latitude: 47.2335, longitude: -123.1475, elevation: 83 },
  { id: "7", name: "GoJump Oceanside", country: "United States", city: "Oceanside CA", latitude: 33.218, longitude: -117.3515, elevation: 8 },
  { id: "8", name: "Skydive Perris", country: "United States", city: "Perris CA", latitude: 33.7646, longitude: -117.219, elevation: 431 },
  { id: "9", name: "Air Bears - Skydiving Club at Berkeley", country: "United States", city: "Berkeley CA", latitude: null, longitude: null, elevation: 0 },
  { id: "10", name: "The California Parachute Club", country: "United States", city: "Livermore CA", latitude: null, longitude: null, elevation: 0 },
  { id: "11", name: "Skydive UC Davis", country: "United States", city: "Davis CA", latitude: null, longitude: null, elevation: 0 },
  { id: "12", name: "UConn Skydiving Club", country: "United States", city: "Ellington CT", latitude: null, longitude: null, elevation: 0 },
  { id: "13", name: "Blue Skies Skydiving Club", country: "United States", city: "Indianapolis IN", latitude: null, longitude: null, elevation: 0 },
  { id: "14", name: "Skydive Broncos at Western Michigan University", country: "United States", city: "Ann Arbor MI", latitude: null, longitude: null, elevation: 0 },
  { id: "15", name: "Skydive Alabama", country: "United States", city: "Vinemont AL", latitude: null, longitude: null, elevation: 0 },
  { id: "16", name: "Skydive the Gulf", country: "United States", city: "Elberta AL", latitude: null, longitude: null, elevation: 0 },
  { id: "17", name: "Alaska Skydive Center", country: "United States", city: "Anchorage AK", latitude: null, longitude: null, elevation: 0 },
  { id: "18", name: "Complete Parachute Solutions Bishop", country: "United States", city: "Bishop CA", latitude: null, longitude: null, elevation: 0 },
  { id: "19", name: "Complete Parachute Solutions Tactical Training Facility", country: "United States", city: "Coolidge AZ", latitude: null, longitude: null, elevation: 0 },
  { id: "20", name: "Phoenix Skydive Center", country: "United States", city: "Phoenix AZ", latitude: null, longitude: null, elevation: 0 },
  { id: "21", name: "Skydive Buckeye", country: "United States", city: "Phoenix AZ", latitude: null, longitude: null, elevation: 0 },
  { id: "22", name: "Skydive Marana", country: "United States", city: "Tucson AZ", latitude: null, longitude: null, elevation: 0 },
  { id: "23", name: "Skydive Phoenix", country: "United States", city: "Maricopa AZ", latitude: null, longitude: null, elevation: 0 },
  { id: "24", name: "Paradise Valley Skydiving", country: "United States", city: "Clarksville AR", latitude: null, longitude: null, elevation: 0 },
  { id: "25", name: "Skydive Fayetteville", country: "United States", city: "Fayetteville AR", latitude: null, longitude: null, elevation: 0 },
  { id: "26", name: "Bay Area Skydiving", country: "United States", city: "San Francisco CA", latitude: null, longitude: null, elevation: 0 },
  { id: "27", name: "GoJump Oceanside", country: "United States", city: "San Diego CA", latitude: null, longitude: null, elevation: 0 },
  { id: "28", name: "iSkydive America - Los Angeles", country: "United States", city: "Los Angeles CA", latitude: null, longitude: null, elevation: 0 },
  { id: "29", name: "Military Freefall Solutions Inc.", country: "United States", city: "Yuma AZ", latitude: null, longitude: null, elevation: 0 },
  { id: "30", name: "NorCal Skydiving", country: "United States", city: "San Francisco CA", latitude: null, longitude: null, elevation: 0 },
  { id: "31", name: "Pacific Coast Skydiving", country: "United States", city: "San Diego CA", latitude: null, longitude: null, elevation: 0 },
  { id: "32", name: "Porterville Training Facility", country: "United States", city: "Bakersfield CA", latitude: null, longitude: null, elevation: 0 },
  { id: "33", name: "Silicon Valley Skydiving", country: "United States", city: "San Jose CA", latitude: null, longitude: null, elevation: 0 },
  { id: "34", name: "SkyDance SkyDiving", country: "United States", city: "Davis CA", latitude: null, longitude: null, elevation: 0 },
  { id: "35", name: "Skydive California", country: "United States", city: "Tracy CA", latitude: null, longitude: null, elevation: 0 },
  { id: "36", name: "Skydive Elsinore", country: "United States", city: "Lake Elsinore CA", latitude: null, longitude: null, elevation: 0 },
  { id: "37", name: "Skydive Golden Gate", country: "United States", city: "Novato CA", latitude: null, longitude: null, elevation: 0 },
  { id: "38", name: "Skydive Madera", country: "United States", city: "Fresno CA", latitude: null, longitude: null, elevation: 0 },
  { id: "39", name: "Skydive Mt. Whitney", country: "United States", city: "Lone Pine CA", latitude: null, longitude: null, elevation: 0 },
  { id: "40", name: "Skydive Perris", country: "United States", city: "Los Angeles CA", latitude: null, longitude: null, elevation: 0 },
  { id: "41", name: "Skydive San Diego", country: "United States", city: "San Diego CA", latitude: null, longitude: null, elevation: 0 },
  { id: "42", name: "Skydive San Joaquin Valley", country: "United States", city: "Los Angeles CA", latitude: null, longitude: null, elevation: 0 },
  { id: "43", name: "Skydive Santa Barbara", country: "United States", city: "Santa Barbara CA", latitude: null, longitude: null, elevation: 0 },
  { id: "44", name: "Skydive Yosemite", country: "United States", city: "Yosemite CA", latitude: null, longitude: null, elevation: 0 },
  { id: "45", name: "High Sky Adventure Parachute Club", country: "United States", city: "Canon City CO", latitude: null, longitude: null, elevation: 0 },
  { id: "46", name: "Mile-Hi Skydiving Center Inc.", country: "United States", city: "Denver CO", latitude: null, longitude: null, elevation: 0 },
  { id: "47", name: "Orange Skies Free Fall Center", country: "United States", city: "Denver CO", latitude: null, longitude: null, elevation: 0 },
  { id: "48", name: "Skydive Colorado", country: "United States", city: "Denver CO", latitude: null, longitude: null, elevation: 0 },
  { id: "49", name: "Skydive Colorado Springs", country: "United States", city: "Colorado Springs CO", latitude: null, longitude: null, elevation: 0 },
  { id: "50", name: "Connecticut Parachutists Inc.", country: "United States", city: "Hartford CT", latitude: null, longitude: null, elevation: 0 },
  { id: "51", name: "Skydive Danielson", country: "United States", city: "Providence RI", latitude: null, longitude: null, elevation: 0 },
  { id: "52", name: "Florida Skydive", country: "United States", city: "Coleman FL", latitude: null, longitude: null, elevation: 0 },
  { id: "53", name: "Skydive America - Miami", country: "United States", city: "Miami FL", latitude: null, longitude: null, elevation: 0 },
  { id: "54", name: "Jump Florida Skydiving", country: "United States", city: "Orlando FL", latitude: null, longitude: null, elevation: 0 },
  { id: "55", name: "Miami Skydiving Center", country: "United States", city: "Miami FL", latitude: null, longitude: null, elevation: 0 },
  { id: "56", name: "Skydive Amelia Island", country: "United States", city: "Fernandina Beach FL", latitude: null, longitude: null, elevation: 0 },
  { id: "57", name: "Skydive City Zephyrhills", country: "United States", city: "Zephyrhills FL", latitude: null, longitude: null, elevation: 0 },
  { id: "58", name: "Skydive DeLand Inc.", country: "United States", city: "Orlando FL", latitude: null, longitude: null, elevation: 0 },
  { id: "59", name: "Skydive Key West", country: "United States", city: "Key West FL", latitude: null, longitude: null, elevation: 0 },
  { id: "60", name: "Skydive Palatka", country: "United States", city: "Jacksonville FL", latitude: null, longitude: null, elevation: 0 },
  { id: "61", name: "Skydive Palm Beach", country: "United States", city: "Wellington FL", latitude: null, longitude: null, elevation: 0 },
  { id: "62", name: "Skydive Panama City", country: "United States", city: "Panama City FL", latitude: null, longitude: null, elevation: 0 },
  { id: "63", name: "Skydive Sebastian", country: "United States", city: "Orlando FL", latitude: null, longitude: null, elevation: 0 },
  { id: "64", name: "Skydive Space Center Inc.", country: "United States", city: "Titusville FL", latitude: null, longitude: null, elevation: 0 },
  { id: "65", name: "Skydive Spaceland-Clewiston", country: "United States", city: "Ft. Lauderdale FL", latitude: null, longitude: null, elevation: 0 },
  { id: "66", name: "Skydive SW Florida Club", country: "United States", city: "Punta Gorda FL", latitude: null, longitude: null, elevation: 0 },
  { id: "67", name: "Jump Georgia Skydiving", country: "United States", city: "Savannah GA", latitude: null, longitude: null, elevation: 0 },
  { id: "68", name: "Skydive Atlanta", country: "United States", city: "Atlanta GA", latitude: null, longitude: null, elevation: 0 },
  { id: "69", name: "Skydive Georgia", country: "United States", city: "Cedartown GA", latitude: null, longitude: null, elevation: 0 },
  { id: "70", name: "Skydive Monroe", country: "United States", city: "Atlanta GA", latitude: null, longitude: null, elevation: 0 },
  { id: "71", name: "Skydive South Atlanta", country: "United States", city: "Atlanta GA", latitude: null, longitude: null, elevation: 0 },
  { id: "72", name: "Skydive The Farm", country: "United States", city: "Atlanta GA", latitude: null, longitude: null, elevation: 0 },
  { id: "73", name: "Big Island Gravity", country: "United States", city: "Kailua Kona HI", latitude: null, longitude: null, elevation: 0 },
  { id: "74", name: "GoJump Hawaii", country: "United States", city: "Honolulu HI", latitude: null, longitude: null, elevation: 0 },
  { id: "75", name: "Maui Skydiving", country: "United States", city: "Kahului HI", latitude: null, longitude: null, elevation: 0 },
  { id: "76", name: "DZONE Skydiving-Boise", country: "United States", city: "Boise ID", latitude: null, longitude: null, elevation: 0 },
  { id: "77", name: "Skydive Skydown", country: "United States", city: "Caldwell ID", latitude: null, longitude: null, elevation: 0 },
  { id: "78", name: "Chicagoland Skydiving Center", country: "United States", city: "Chicago IL", latitude: null, longitude: null, elevation: 0 },
  { id: "79", name: "Mid-America Sport Parachute Club", country: "United States", city: "Springfield IL", latitude: null, longitude: null, elevation: 0 },
  { id: "80", name: "SEMO Skydiving", country: "United States", city: "Cape Girardeau IL", latitude: null, longitude: null, elevation: 0 },
  { id: "81", name: "Skydive Chicago Inc.", country: "United States", city: "Chicago IL", latitude: null, longitude: null, elevation: 0 },
  { id: "82", name: "Skydive Indianapolis", country: "United States", city: "Indianapolis IN", latitude: null, longitude: null, elevation: 0 },
  { id: "83", name: "Des Moines Skydivers", country: "United States", city: "Des Moines IA", latitude: null, longitude: null, elevation: 0 },
  { id: "84", name: "Skydive Iowa", country: "United States", city: "Des Moines IA", latitude: null, longitude: null, elevation: 0 },
  { id: "85", name: "Kansas State University Parachute Club", country: "United States", city: "Salina KS", latitude: null, longitude: null, elevation: 0 },
  { id: "86", name: "Skydive Kentucky", country: "United States", city: "Louisville KY", latitude: null, longitude: null, elevation: 0 },
  { id: "87", name: "Cloud Chasers", country: "United States", city: "Slidell LA", latitude: null, longitude: null, elevation: 0 },
  { id: "88", name: "Skydive Coastal Maine", country: "United States", city: "Portland ME", latitude: null, longitude: null, elevation: 0 },
  { id: "89", name: "Skydive New England", country: "United States", city: "Lebanon ME", latitude: null, longitude: null, elevation: 0 },
  { id: "90", name: "Skydive Chesapeake", country: "United States", city: "Annapolis MD", latitude: null, longitude: null, elevation: 0 },
  { id: "91", name: "Skydive Ocean City", country: "United States", city: "Ocean City MD", latitude: null, longitude: null, elevation: 0 },
  { id: "92", name: "Jumptown/MSRC Inc.", country: "United States", city: "Boston MA", latitude: null, longitude: null, elevation: 0 },
  { id: "93", name: "Pepperell Skydiving Center", country: "United States", city: "Boston MA", latitude: null, longitude: null, elevation: 0 },
  { id: "94", name: "iSkydive America - Charlevoix", country: "United States", city: "Traverse City MI", latitude: null, longitude: null, elevation: 0 },
  { id: "95", name: "iSkydive America - Detroit", country: "United States", city: "East Lansing MI", latitude: null, longitude: null, elevation: 0 },
  { id: "96", name: "Midwest Freefall Sport Parachute Club Inc.", country: "United States", city: "Detroit MI", latitude: null, longitude: null, elevation: 0 },
  { id: "97", name: "Skydive Grand Haven", country: "United States", city: "Grand Haven MI", latitude: null, longitude: null, elevation: 0 },
  { id: "98", name: "Skydive TC", country: "United States", city: "Traverse City MI", latitude: null, longitude: null, elevation: 0 },
  { id: "99", name: "Skydive Tecumseh", country: "United States", city: "Jackson MI", latitude: null, longitude: null, elevation: 0 },
  { id: "100", name: "Skydive Adventures", country: "United States", city: "Luverne MN", latitude: null, longitude: null, elevation: 0 },
  { id: "101", name: "Skydive Northstar", country: "United States", city: "Twin Cities MN", latitude: null, longitude: null, elevation: 0 },
  { id: "102", name: "Falcon Skydiving", country: "United States", city: "Kansas City MO", latitude: null, longitude: null, elevation: 0 },
  { id: "103", name: "Flight Providers LLC", country: "United States", city: "Springfield MO", latitude: null, longitude: null, elevation: 0 },
  { id: "104", name: "Ozarks Skydive Center", country: "United States", city: "Springfield MO", latitude: null, longitude: null, elevation: 0 },
  { id: "105", name: "SEMO Skydiving", country: "United States", city: "Cape Girardeau MO", latitude: null, longitude: null, elevation: 0 },
  { id: "106", name: "Skydive STL", country: "United States", city: "St. Louis MO", latitude: null, longitude: null, elevation: 0 },
  { id: "107", name: "DZONE Skydiving-Bozeman", country: "United States", city: "Bozeman MT", latitude: null, longitude: null, elevation: 0 },
  { id: "108", name: "Meadow Peak Skydiving", country: "United States", city: "Kalispell MT", latitude: null, longitude: null, elevation: 0 },
  { id: "109", name: "Skydive Missoula", country: "United States", city: "Missoula MT", latitude: null, longitude: null, elevation: 0 },
  { id: "110", name: "Skydive Whitefish", country: "United States", city: "Whitefish MT", latitude: null, longitude: null, elevation: 0 },
  { id: "111", name: "Jump Omaha", country: "United States", city: "Plattsmouth NE", latitude: null, longitude: null, elevation: 0 },
  { id: "112", name: "Lincoln Sport Parachute Club", country: "United States", city: "Lincoln NE", latitude: null, longitude: null, elevation: 0 },
  { id: "113", name: "Fyrosity", country: "United States", city: "Overton NV", latitude: null, longitude: null, elevation: 0 },
  { id: "114", name: "GoJump Las Vegas", country: "United States", city: "Las Vegas NV", latitude: null, longitude: null, elevation: 0 },
  { id: "115", name: "Sin City Skydiving", country: "United States", city: "Las Vegas NV", latitude: null, longitude: null, elevation: 0 },
  { id: "116", name: "Skydive Lake Tahoe", country: "United States", city: "South Lake Tahoe NV", latitude: null, longitude: null, elevation: 0 },
  { id: "117", name: "Skydive Las Vegas", country: "United States", city: "Las Vegas NV", latitude: null, longitude: null, elevation: 0 },
  { id: "118", name: "Skydive Mesquite", country: "United States", city: "Las Vegas NV", latitude: null, longitude: null, elevation: 0 },
  { id: "119", name: "iSkydive America - New York City", country: "United States", city: "New York City NY", latitude: null, longitude: null, elevation: 0 },
  { id: "120", name: "Skydive Cross Keys", country: "United States", city: "Philadelphia PA", latitude: null, longitude: null, elevation: 0 },
  { id: "121", name: "Skydive East Coast", country: "United States", city: "Atlantic City NJ", latitude: null, longitude: null, elevation: 0 },
  { id: "122", name: "Skydive Sussex", country: "United States", city: "New York City NY", latitude: null, longitude: null, elevation: 0 },
  { id: "123", name: "Sun City Skydive", country: "United States", city: "Santa Teresa NM", latitude: null, longitude: null, elevation: 0 },
  { id: "124", name: "Viva Skydive", country: "United States", city: "Albuquerque NM", latitude: null, longitude: null, elevation: 0 },
  { id: "125", name: "Blue Sky Ranch", country: "United States", city: "New York NY", latitude: null, longitude: null, elevation: 0 },
  { id: "126", name: "Just Jump Skydiving", country: "United States", city: "Norwich NY", latitude: null, longitude: null, elevation: 0 },
  { id: "127", name: "Long Island Skydiving Center", country: "United States", city: "New York NY", latitude: null, longitude: null, elevation: 0 },
  { id: "128", name: "Rochester Skydivers", country: "United States", city: "Rochester NY", latitude: null, longitude: null, elevation: 0 },
  { id: "129", name: "Skydive Central New York", country: "United States", city: "Syracuse NY", latitude: null, longitude: null, elevation: 0 },
  { id: "130", name: "Skydive Saratoga", country: "United States", city: "Saratoga Springs NY", latitude: null, longitude: null, elevation: 0 },
  { id: "131", name: "Skydive Seneca Lake", country: "United States", city: "Geneva NY", latitude: null, longitude: null, elevation: 0 },
  { id: "132", name: "Skydive The Falls", country: "United States", city: "Niagara Falls NY", latitude: null, longitude: null, elevation: 0 },
  { id: "133", name: "Skydive The Ranch", country: "United States", city: "New York NY", latitude: null, longitude: null, elevation: 0 },
  { id: "134", name: "WNYSkydiving", country: "United States", city: "Buffalo NY", latitude: null, longitude: null, elevation: 0 },
  { id: "135", name: "Crystal Coast Skydiving", country: "United States", city: "Beaufort NC", latitude: null, longitude: null, elevation: 0 },
  { id: "136", name: "Piedmont Skydiving", country: "United States", city: "Charlotte NC", latitude: null, longitude: null, elevation: 0 },
  { id: "137", name: "Skydive Central North Carolina LLC", country: "United States", city: "Charlotte NC", latitude: null, longitude: null, elevation: 0 },
  { id: "138", name: "Skydive Coastal Carolinas", country: "United States", city: "Wilmington NC", latitude: null, longitude: null, elevation: 0 },
  { id: "139", name: "Skydive OBX", country: "United States", city: "Norfolk VA", latitude: null, longitude: null, elevation: 0 },
  { id: "140", name: "Skydive Paraclete XP", country: "United States", city: "Fayetteville NC", latitude: null, longitude: null, elevation: 0 },
  { id: "141", name: "Skydive Fargo Inc.", country: "United States", city: "Fargo ND", latitude: null, longitude: null, elevation: 0 },
  { id: "142", name: "Aerohio Skydiving Center", country: "United States", city: "Ashland OH", latitude: null, longitude: null, elevation: 0 },
  { id: "143", name: "Alliance Sport Parachute Club", country: "United States", city: "Pittsburgh PA", latitude: null, longitude: null, elevation: 0 },
  { id: "144", name: "Canton Air Sports", country: "United States", city: "Akron OH", latitude: null, longitude: null, elevation: 0 },
  { id: "145", name: "Cleveland Skydiving Center", country: "United States", city: "Cleveland OH", latitude: null, longitude: null, elevation: 0 },
  { id: "146", name: "Skydive Cincinnati", country: "United States", city: "Cincinnati OH", latitude: null, longitude: null, elevation: 0 },
  { id: "147", name: "Start Skydiving", country: "United States", city: "Cincinnati OH", latitude: null, longitude: null, elevation: 0 },
  { id: "148", name: "Oklahoma Skydiving Center", country: "United States", city: "Oklahoma City OK", latitude: null, longitude: null, elevation: 0 },
  { id: "149", name: "Skydive Airtight", country: "United States", city: "Tulsa OK", latitude: null, longitude: null, elevation: 0 },
  { id: "150", name: "Skydive Cherokee", country: "United States", city: "Muskogee OK", latitude: null, longitude: null, elevation: 0 },
  { id: "151", name: "Eugene Skydive", country: "United States", city: "Eugene OR", latitude: null, longitude: null, elevation: 0 },
  { id: "152", name: "Pacific Northwest Skydiving Center", country: "United States", city: "Portland OR", latitude: null, longitude: null, elevation: 0 },
  { id: "153", name: "Skydive Bend", country: "United States", city: "Bend OR", latitude: null, longitude: null, elevation: 0 },
  { id: "154", name: "Skydive Oregon Inc.", country: "United States", city: "Molalla OR", latitude: null, longitude: null, elevation: 0 },
  { id: "155", name: "Above The Poconos Skydivers PA Skydive Center", country: "United States", city: "Wilkes-Barre PA", latitude: null, longitude: null, elevation: 0 },
  { id: "156", name: "Maytown Sport Parachute Club", country: "United States", city: "Harrisburg PA", latitude: null, longitude: null, elevation: 0 },
  { id: "157", name: "Pegasus Skydive Center", country: "United States", city: "Allentown PA", latitude: null, longitude: null, elevation: 0 },
  { id: "158", name: "Skydive NEPA", country: "United States", city: "Scranton PA", latitude: null, longitude: null, elevation: 0 },
  { id: "159", name: "Skydive Pennsylvania", country: "United States", city: "Pittsburgh PA", latitude: null, longitude: null, elevation: 0 },
  { id: "160", name: "Skydive Philadelphia", country: "United States", city: "Philadelphia PA", latitude: null, longitude: null, elevation: 0 },
  { id: "161", name: "Skydive Puerto Rico", country: "United States", city: "San Juan PR", latitude: null, longitude: null, elevation: 0 },
  { id: "162", name: "Boston Skydive Center", country: "United States", city: "Providence RI", latitude: null, longitude: null, elevation: 0 },
  { id: "163", name: "Skydive Newport", country: "United States", city: "Newport RI", latitude: null, longitude: null, elevation: 0 },
  { id: "164", name: "Flying Tigers Sport Parachute Center", country: "United States", city: "Anderson SC", latitude: null, longitude: null, elevation: 0 },
  { id: "165", name: "Skydive Carolina!", country: "United States", city: "Charlotte NC", latitude: null, longitude: null, elevation: 0 },
  { id: "166", name: "Upstate Skydiving LLC", country: "United States", city: "Union SC", latitude: null, longitude: null, elevation: 0 },
  { id: "167", name: "Chattanooga Skydiving Company", country: "United States", city: "Chattanooga TN", latitude: null, longitude: null, elevation: 0 },
  { id: "168", name: "Jump TN", country: "United States", city: "Greeneville TN", latitude: null, longitude: null, elevation: 0 },
  { id: "169", name: "Music City Skydiving", country: "United States", city: "Nashville TN", latitude: null, longitude: null, elevation: 0 },
  { id: "170", name: "iSkydive America - Dallas", country: "United States", city: "Dallas TX", latitude: null, longitude: null, elevation: 0 },
  { id: "171", name: "Skydive Castroville", country: "United States", city: "San Antonio TX", latitude: null, longitude: null, elevation: 0 },
  { id: "172", name: "Skydive East Texas", country: "United States", city: "Longview TX", latitude: null, longitude: null, elevation: 0 },
  { id: "173", name: "Skydive Spaceland-Dallas", country: "United States", city: "Dallas TX", latitude: null, longitude: null, elevation: 0 },
  { id: "174", name: "Skydive Spaceland-Houston", country: "United States", city: "Houston TX", latitude: null, longitude: null, elevation: 0 },
  { id: "175", name: "Skydive Spaceland-San Marcos", country: "United States", city: "Austin TX", latitude: null, longitude: null, elevation: 0 },
  { id: "176", name: "Skylark Skydive", country: "United States", city: "Austin TX", latitude: null, longitude: null, elevation: 0 },
  { id: "177", name: "Texas Skydiving", country: "United States", city: "Austin TX", latitude: null, longitude: null, elevation: 0 },
  { id: "178", name: "Ogden Skydiving Center", country: "United States", city: "Salt Lake City UT", latitude: null, longitude: null, elevation: 0 },
  { id: "179", name: "Skydive Moab", country: "United States", city: "Grand Junction CO", latitude: null, longitude: null, elevation: 0 },
  { id: "180", name: "Skydive the Wasatch", country: "United States", city: "Salt Lake City UT", latitude: null, longitude: null, elevation: 0 },
  { id: "181", name: "Skydive Utah", country: "United States", city: "Salt Lake City UT", latitude: null, longitude: null, elevation: 0 },
  { id: "182", name: "Malone Parachute Club", country: "United States", city: "Burlington VT", latitude: null, longitude: null, elevation: 0 },
  { id: "183", name: "Vermont Skydiving Adventures Inc.", country: "United States", city: "Burlington VT", latitude: null, longitude: null, elevation: 0 },
  { id: "184", name: "iSkydive America - Washington D.C.", country: "United States", city: "Washington DC", latitude: null, longitude: null, elevation: 0 },
  { id: "185", name: "No Limits Skydiving - Victoria", country: "United States", city: "Victoria TX", latitude: null, longitude: null, elevation: 0 },
  { id: "186", name: "No Limits Skydiving - West Point", country: "United States", city: "Richmond VA", latitude: null, longitude: null, elevation: 0 },
  { id: "187", name: "Skydive Front Royal", country: "United States", city: "Washington DC", latitude: null, longitude: null, elevation: 0 },
  { id: "188", name: "Skydive East Tennessee", country: "United States", city: "Knoxville TN", latitude: null, longitude: null, elevation: 0 },
  { id: "189", name: "Skydive Orange Inc.", country: "United States", city: "Washington DC", latitude: null, longitude: null, elevation: 0 },
  { id: "190", name: "Skydive Shenandoah", country: "United States", city: "Washington DC", latitude: null, longitude: null, elevation: 0 },
  { id: "191", name: "Skydive Suffolk", country: "United States", city: "Virginia Beach VA", latitude: null, longitude: null, elevation: 0 },
  { id: "192", name: "West Tennessee Skydiving", country: "United States", city: "Memphis TN", latitude: null, longitude: null, elevation: 0 },
  { id: "193", name: "Kapowsin Air Sports", country: "United States", city: "Olympia WA", latitude: null, longitude: null, elevation: 0 },
  { id: "194", name: "Rattlesnake Mountain Skydiving", country: "United States", city: "Yakima WA", latitude: null, longitude: null, elevation: 0 },
  { id: "195", name: "Skydive Chelan", country: "United States", city: "Wenatchee WA", latitude: null, longitude: null, elevation: 0 },
  { id: "196", name: "Skydive Snohomish Inc.", country: "United States", city: "Seattle WA", latitude: null, longitude: null, elevation: 0 },
  { id: "197", name: "Skydive Toledo", country: "United States", city: "Toledo OH", latitude: null, longitude: null, elevation: 0 },
  { id: "198", name: "Skydive West Plains", country: "United States", city: "Spokane WA", latitude: null, longitude: null, elevation: 0 },
  { id: "199", name: "West Virginia Skydivers Inc.", country: "United States", city: "Huntington WV", latitude: null, longitude: null, elevation: 0 },
  { id: "200", name: "Seven Hills Skydivers of Madison WI", country: "United States", city: "Madison WI", latitude: null, longitude: null, elevation: 0 },
  { id: "201", name: "Skydive Duluth", country: "United States", city: "Duluth MN", latitude: null, longitude: null, elevation: 0 },
  { id: "202", name: "Skydive Freefall Adventure LLC", country: "United States", city: "Green Bay WI", latitude: null, longitude: null, elevation: 0 },
  { id: "203", name: "Skydive Midwest", country: "United States", city: "Chicago IL", latitude: null, longitude: null, elevation: 0 },
  { id: "204", name: "Skydive Milwaukee/Sky Knights Sport Parachute Club", country: "United States", city: "Milwaukee WI", latitude: null, longitude: null, elevation: 0 },
  { id: "205", name: "Skydive Twin Cities", country: "United States", city: "St. Paul MN", latitude: null, longitude: null, elevation: 0 },
  { id: "206", name: "Skydive Wissota/Indianhead SPC", country: "United States", city: "Chippewa Falls WI", latitude: null, longitude: null, elevation: 0 },
  { id: "207", name: "Skydive Angola", country: "Angola", city: "Aeroporto de Cabóledo", latitude: null, longitude: null, elevation: 0 },
  { id: "208", name: "Skydive Chascomus", country: "Argentina", city: "Buenos Aires", latitude: null, longitude: null, elevation: 0 },
  { id: "209", name: "Paracaidismo Alta Gracia", country: "Argentina", city: "Cordoba", latitude: null, longitude: null, elevation: 0 },
  { id: "210", name: "Skydive Armheli", country: "Armenia", city: "Yerevan", latitude: null, longitude: null, elevation: 0 },
  { id: "211", name: "Skydive The Bahamas", country: "Bahamas", city: "Freeport", latitude: null, longitude: null, elevation: 0 },
  { id: "212", name: "Skydive Spa", country: "Belgium", city: "Liege", latitude: null, longitude: null, elevation: 0 },
  { id: "213", name: "Skydive Botswana", country: "Botswana", city: "Gaborone", latitude: null, longitude: null, elevation: 0 },
  { id: "214", name: "Federacao Paulista De Paraquedismo", country: "Brazil", city: "Boituva", latitude: null, longitude: null, elevation: 0 },
  { id: "215", name: "Skydive Sofia", country: "Bulgaria", city: "Sofia", latitude: null, longitude: null, elevation: 0 },
  { id: "216", name: "Airborne Petawawa", country: "Canada", city: "Petawawa", latitude: null, longitude: null, elevation: 0 },
  { id: "217", name: "Alberta Skydive Central", country: "Canada", city: "Edmonton", latitude: null, longitude: null, elevation: 0 },
  { id: "218", name: "Parachutisme Adrenaline Trois-Rivieres", country: "Canada", city: "Quebec", latitude: null, longitude: null, elevation: 0 },
  { id: "219", name: "Parachutisme Atmosphair", country: "Canada", city: "Quebec", latitude: null, longitude: null, elevation: 0 },
  { id: "220", name: "Parachute Montreal Rive-Nord", country: "Canada", city: "Montreal", latitude: null, longitude: null, elevation: 0 },
  { id: "221", name: "Parachute Montreal Rive-Sud", country: "Canada", city: "Montreal", latitude: null, longitude: null, elevation: 0 },
  { id: "222", name: "Parachute Victoriaville", country: "Canada", city: "Montreal", latitude: null, longitude: null, elevation: 0 },
  { id: "223", name: "Skydive Burnaby", country: "Canada", city: "Vancouver", latitude: null, longitude: null, elevation: 0 },
  { id: "224", name: "Skydive Ontario", country: "Canada", city: "Toronto", latitude: null, longitude: null, elevation: 0 },
  { id: "225", name: "Skydive Vancouver", country: "Canada", city: "Vancouver", latitude: null, longitude: null, elevation: 0 },
  { id: "226", name: "Skydive Vancouver Island", country: "Canada", city: "Nanaimo", latitude: null, longitude: null, elevation: 0 },
  { id: "227", name: "Skydive Aloha El Tapihue", country: "Chile", city: "Santiago", latitude: null, longitude: null, elevation: 0 },
  { id: "228", name: "Skydive Andes", country: "Chile", city: "Santiago", latitude: null, longitude: null, elevation: 0 },
  { id: "229", name: "BT Chengdu Skydive", country: "China", city: "Chengdu", latitude: null, longitude: null, elevation: 0 },
  { id: "230", name: "China Skydivers-Yingfei", country: "China", city: "Guangzhou", latitude: null, longitude: null, elevation: 0 },
  { id: "231", name: "Skydive Beijing", country: "China", city: "Beijing", latitude: null, longitude: null, elevation: 0 },
  { id: "232", name: "Skydive Hailing Island", country: "China", city: "Yangjiang", latitude: null, longitude: null, elevation: 0 },
  { id: "233", name: "Skydive Hainan", country: "China", city: "Danzhou", latitude: null, longitude: null, elevation: 0 },
  { id: "234", name: "Skydive Panda - Chongqing", country: "China", city: "Chongqing", latitude: null, longitude: null, elevation: 0 },
  { id: "235", name: "Skydive Riyue Bay", country: "China", city: "Wanning", latitude: null, longitude: null, elevation: 0 },
  { id: "236", name: "Skydive Taiwan", country: "China", city: "Taitung", latitude: null, longitude: null, elevation: 0 },
  { id: "237", name: "Skydive Thru Quero Saltar", country: "China", city: "São Paulo", latitude: null, longitude: null, elevation: 0 },
  { id: "238", name: "Skydive Weiand", country: "China", city: "Haikou", latitude: null, longitude: null, elevation: 0 },
  { id: "239", name: "Skydive ZhuHai", country: "China", city: "Zhuhai", latitude: null, longitude: null, elevation: 0 },
  { id: "240", name: "Yan Huang Skydive", country: "China", city: "Zhengzhou", latitude: null, longitude: null, elevation: 0 },
  { id: "241", name: "Aire Skydive", country: "Colombia", city: "Medellin", latitude: null, longitude: null, elevation: 0 },
  { id: "242", name: "Epico Skydive", country: "Colombia", city: "Barranquilla", latitude: null, longitude: null, elevation: 0 },
  { id: "243", name: "Skydive Golden", country: "Colombia", city: "Girardot", latitude: null, longitude: null, elevation: 0 },
  { id: "244", name: "Xielo Skydive", country: "Colombia", city: "Girardot", latitude: null, longitude: null, elevation: 0 },
  { id: "245", name: "Desafio Vertical", country: "Costa Rica", city: "Jaco", latitude: null, longitude: null, elevation: 0 },
  { id: "246", name: "Skydive Croatia", country: "Croatia", city: "Zagreb", latitude: null, longitude: null, elevation: 0 },
  { id: "247", name: "Skydive Zadar", country: "Croatia", city: "Zadar", latitude: null, longitude: null, elevation: 0 },
  { id: "248", name: "Dropzone Prostejov", country: "Czech Republic", city: "Brno", latitude: null, longitude: null, elevation: 0 },
  { id: "249", name: "DZ Pribram", country: "Czech Republic", city: "Prague", latitude: null, longitude: null, elevation: 0 },
  { id: "250", name: "International Pink Parachute Club", country: "Czech Republic", city: "Prague", latitude: null, longitude: null, elevation: 0 },
  { id: "251", name: "Dropzone Denmark", country: "Denmark", city: "Aarhus", latitude: null, longitude: null, elevation: 0 },
  { id: "252", name: "Condor de los Andes", country: "Ecuador", city: "Quito", latitude: null, longitude: null, elevation: 0 },
  { id: "253", name: "Los Garrapateros Paracaidismo", country: "Ecuador", city: "Guayaquil", latitude: null, longitude: null, elevation: 0 },
  { id: "254", name: "Skydive La Celeste", country: "Ecuador", city: "La Concordia", latitude: null, longitude: null, elevation: 0 },
  { id: "255", name: "Skydive Egypt - Jump Like a Pharaoh", country: "Egypt", city: "Cairo", latitude: null, longitude: null, elevation: 0 },
  { id: "256", name: "Skydive Pharaohs", country: "Egypt", city: "Cairo", latitude: null, longitude: null, elevation: 0 },
  { id: "257", name: "Skydive San Miguel", country: "El Salvador", city: "San Miguel", latitude: null, longitude: null, elevation: 0 },
  { id: "258", name: "Skydive Estonia", country: "Estonia", city: "Tallinn", latitude: null, longitude: null, elevation: 0 },
  { id: "259", name: "Skydive Karjala", country: "Finland", city: "Imatra", latitude: null, longitude: null, elevation: 0 },
  { id: "260", name: "Air Play Parachutisme", country: "France", city: "Cannes", latitude: null, longitude: null, elevation: 0 },
  { id: "261", name: "Fly 974 Tandem", country: "France", city: "Saint Pierre Reunion", latitude: null, longitude: null, elevation: 0 },
  { id: "262", name: "Paris-Jump", country: "France", city: "Paris", latitude: null, longitude: null, elevation: 0 },
  { id: "263", name: "Aircrew & Airfox Skydiving Academy", country: "Germany", city: "Frankfurt", latitude: null, longitude: null, elevation: 0 },
  { id: "264", name: "FSC Suedpfalz E.V.", country: "Germany", city: "Frankfurt", latitude: null, longitude: null, elevation: 0 },
  { id: "265", name: "Skydive Saar (FSZ - Saar)", country: "Germany", city: "Saarlouis", latitude: null, longitude: null, elevation: 0 },
  { id: "266", name: "Skydive Saulgau", country: "Germany", city: "Ulm", latitude: null, longitude: null, elevation: 0 },
  { id: "267", name: "Hellenic Skydivers", country: "Greece", city: "Athens", latitude: null, longitude: null, elevation: 0 },
  { id: "268", name: "Skydive Athens", country: "Greece", city: "Athens", latitude: null, longitude: null, elevation: 0 },
  { id: "269", name: "Skydive Attica", country: "Greece", city: "Athens", latitude: null, longitude: null, elevation: 0 },
  { id: "270", name: "Skydive Greece", country: "Greece", city: "Athens", latitude: null, longitude: null, elevation: 0 },
  { id: "271", name: "Skydive Thessaloniki", country: "Greece", city: "Thessaloniki", latitude: null, longitude: null, elevation: 0 },
  { id: "272", name: "Skyhigh India", country: "India", city: "Narnaul", latitude: null, longitude: null, elevation: 0 },
  { id: "273", name: "Irish Parachute Club Ltd.", country: "Ireland", city: "Dublin", latitude: null, longitude: null, elevation: 0 },
  { id: "274", name: "Sky Kef", country: "Israel", city: "Beer Sheva", latitude: null, longitude: null, elevation: 0 },
  { id: "275", name: "Skydive Shamrat (Sky-Jump)", country: "Israel", city: "Tamar", latitude: null, longitude: null, elevation: 0 },
  { id: "276", name: "Body Fly University", country: "Italy", city: "Reggio Emilia", latitude: null, longitude: null, elevation: 0 },
  { id: "277", name: "Fano Sky Team S.S.D.", country: "Italy", city: "Ancona", latitude: null, longitude: null, elevation: 0 },
  { id: "278", name: "Skydive Costa D'Argento", country: "Italy", city: "Rome", latitude: null, longitude: null, elevation: 0 },
  { id: "279", name: "Skydive FlyGang F4F DZone", country: "Italy", city: "Bologna", latitude: null, longitude: null, elevation: 0 },
  { id: "280", name: "Skydive Lucca", country: "Italy", city: "Lucca", latitude: null, longitude: null, elevation: 0 },
  { id: "281", name: "Skydive Sardegna", country: "Italy", city: "Cagliari", latitude: null, longitude: null, elevation: 0 },
  { id: "282", name: "Skydive Thiene", country: "Italy", city: "Vicenza", latitude: null, longitude: null, elevation: 0 },
  { id: "283", name: "Vizone S.S.D.", country: "Italy", city: "Milan", latitude: null, longitude: null, elevation: 0 },
  { id: "284", name: "Skydive Fujioka", country: "Japan", city: "Tokyo", latitude: null, longitude: null, elevation: 0 },
  { id: "285", name: "Skydiving Kansai", country: "Japan", city: "Kyoto", latitude: null, longitude: null, elevation: 0 },
  { id: "286", name: "Tokyo Skydiving Club", country: "Japan", city: "Tokyo", latitude: null, longitude: null, elevation: 0 },
  { id: "287", name: "Go Jump Kenya", country: "Kenya", city: "Mombasa", latitude: null, longitude: null, elevation: 0 },
  { id: "288", name: "Kuwait Skydive & Fly", country: "Kuwait", city: "Kuwait City", latitude: null, longitude: null, elevation: 0 },
  { id: "289", name: "Skydive Latvia", country: "Latvia", city: "Riga", latitude: null, longitude: null, elevation: 0 },
  { id: "290", name: "Skydive Klaipeda", country: "Lithuania", city: "Klaipeda", latitude: null, longitude: null, elevation: 0 },
  { id: "291", name: "Elevate Skydive", country: "Mexico", city: "Cuautla", latitude: null, longitude: null, elevation: 0 },
  { id: "292", name: "Skydive Cuautla", country: "Mexico", city: "Mexico City", latitude: null, longitude: null, elevation: 0 },
  { id: "293", name: "Skydive Monkey Head", country: "Mexico", city: "Mexico City", latitude: null, longitude: null, elevation: 0 },
  { id: "294", name: "Skydive Monterrey", country: "Mexico", city: "Monterrey", latitude: null, longitude: null, elevation: 0 },
  { id: "295", name: "Skydive Paracaidismo Nuevo Leon", country: "Mexico", city: "Monterrey", latitude: null, longitude: null, elevation: 0 },
  { id: "296", name: "Skydive Puebla", country: "Mexico", city: "Puebla", latitude: null, longitude: null, elevation: 0 },
  { id: "297", name: "Beni Mellal DZ", country: "Morocco", city: "Beni Mellal", latitude: null, longitude: null, elevation: 0 },
  { id: "298", name: "Skydive Taroudant", country: "Morocco", city: "Taroudant", latitude: null, longitude: null, elevation: 0 },
  { id: "299", name: "Skydive Tanger", country: "Morocco", city: "Tangier", latitude: null, longitude: null, elevation: 0 },
  { id: "300", name: "Paracentrum Texel", country: "Netherlands", city: "Amsterdam", latitude: null, longitude: null, elevation: 0 },
  { id: "301", name: "Paracaidismo Paracondor Peru", country: "Peru", city: "Lima", latitude: null, longitude: null, elevation: 0 },
  { id: "302", name: "Skydive Santa Fe - Cebu", country: "Philippines", city: "Cebu", latitude: null, longitude: null, elevation: 0 },
  { id: "303", name: "Skydive Siquijor", country: "Philippines", city: "Dumaguete", latitude: null, longitude: null, elevation: 0 },
  { id: "304", name: "Olimpic Skydive", country: "Poland", city: "Wroclaw", latitude: null, longitude: null, elevation: 0 },
  { id: "305", name: "Skydive Algarve", country: "Portugal", city: "Alvor", latitude: null, longitude: null, elevation: 0 },
  { id: "306", name: "Skydive Portugal", country: "Portugal", city: "Evora", latitude: null, longitude: null, elevation: 0 },
  { id: "307", name: "Skydive Taiwan", country: "Republic of China", city: "Taitung", latitude: null, longitude: null, elevation: 0 },
  { id: "308", name: "Skydive Korea", country: "Republic of Korea", city: "Yeoju Station", latitude: null, longitude: null, elevation: 0 },
  { id: "309", name: "Skydive Transilvania", country: "Romania", city: "Cluj-Napoca", latitude: null, longitude: null, elevation: 0 },
  { id: "310", name: "Timisoara Parachute Club Sportiv", country: "Romania", city: "Timisoara", latitude: null, longitude: null, elevation: 0 },
  { id: "311", name: "TNT-Brothers Dropzone", country: "Romania", city: "Bucharest", latitude: null, longitude: null, elevation: 0 },
  { id: "312", name: "TNT-Brothers Seaside", country: "Romania", city: "Constanta", latitude: null, longitude: null, elevation: 0 },
  { id: "313", name: "Krutitcy", country: "Russia", city: "Moscow", latitude: null, longitude: null, elevation: 0 },
  { id: "314", name: "Skydive Vatulino", country: "Russia", city: "Moscow", latitude: null, longitude: null, elevation: 0 },
  { id: "315", name: "Skydive Unique Clouds", country: "Saudi Arabia", city: "Riyadh", latitude: null, longitude: null, elevation: 0 },
  { id: "316", name: "Skydive Slavnica", country: "Slovakia", city: "Trencin", latitude: null, longitude: null, elevation: 0 },
  { id: "317", name: "Skydive Bovec", country: "Slovenia", city: "Nova Gorica", latitude: null, longitude: null, elevation: 0 },
  { id: "318", name: "iJump Gran Canaria", country: "Spain", city: "Las Palmas de Gran Canaria", latitude: null, longitude: null, elevation: 0 },
  { id: "319", name: "Skydive BCN", country: "Spain", city: "Barcelona", latitude: null, longitude: null, elevation: 0 },
  { id: "320", name: "Skydive Empuriabrava", country: "Spain", city: "Barcelona", latitude: null, longitude: null, elevation: 0 },
  { id: "321", name: "Skydive Madrid", country: "Spain", city: "Madrid", latitude: null, longitude: null, elevation: 0 },
  { id: "322", name: "Skydive Spain", country: "Spain", city: "Seville", latitude: null, longitude: null, elevation: 0 },
  { id: "323", name: "Eagles Skydive Sri Lanka-Koggala", country: "Sri Lanka", city: "Koggala", latitude: null, longitude: null, elevation: 0 },
  { id: "324", name: "Skydive Aros", country: "Sweden", city: "Stockholm", latitude: null, longitude: null, elevation: 0 },
  { id: "325", name: "Ecole de Parachutisme de Chateau-d'Oex", country: "Switzerland", city: "Geneva", latitude: null, longitude: null, elevation: 0 },
  { id: "326", name: "Skydive Switzerland", country: "Switzerland", city: "Interlaken", latitude: null, longitude: null, elevation: 0 },
  { id: "327", name: "Skydive Zanzibar", country: "Tanzania", city: "Zanzibar City", latitude: null, longitude: null, elevation: 0 },
  { id: "328", name: "Dropzone Thailand Co. Ltd", country: "Thailand", city: "Bangkok", latitude: null, longitude: null, elevation: 0 },
  { id: "329", name: "Skydive Chiang Mai", country: "Thailand", city: "Chiang Mai", latitude: null, longitude: null, elevation: 0 },
  { id: "330", name: "Skydive Thailand", country: "Thailand", city: "Bangkok", latitude: null, longitude: null, elevation: 0 },
  { id: "331", name: "Thai Sky Adventures Ltd.", country: "Thailand", city: "Bangkok", latitude: null, longitude: null, elevation: 0 },
  { id: "332", name: "Skydive Manavgat", country: "Turkey", city: "Antalya", latitude: null, longitude: null, elevation: 0 },
  { id: "333", name: "Abu Dhabi Skydive", country: "United Arab Emirates", city: "Abu Dhabi", latitude: null, longitude: null, elevation: 0 },
  { id: "334", name: "Skydive Dubai Desert Campus", country: "United Arab Emirates", city: "Dubai", latitude: null, longitude: null, elevation: 0 },
  { id: "335", name: "Sky-High Skydiving", country: "United Kingdom", city: "Newcastle", latitude: null, longitude: null, elevation: 0 },
  { id: "336", name: "Skydive Caribbean", country: "Venezuela", city: "Caracas", latitude: null, longitude: null, elevation: 0 }
];

// Full aircraft list
export const AIRCRAFT_DATABASE = [
  "Antonov AN-2",
  "Beechcraft King Air",
  "Bell 206 JetRanger",
  "Bell 407",
  "CASA C-212",
  "Cessna 172 Skyhawk",
  "Cessna 182",
  "Cessna 206",
  "Cessna 208 Caravan",
  "Cessna Grand Caravan",
  "Dornier G92",
  "Eurocopter AS350",
  "Hot Air Balloon",
  "PAC 750XL",
  "Pilatus PC-6 Porter",
  "Quest Kodiak 100",
  "Robinson R44",
  "Short SC.7 Skyvan",
  "SMG-92 Turbo Finist",
  "Twin Otter",
  "Vulcanair P68",
  "Yakovlev Yak-12"
];